### ISSUE TITLE
Mobile native datepicker control only triggered if date-picker attr is on input element

### ISSUE THREAD

**Issue by jjhampton** [EventBooking/angular-datepicker#8]
@EBMike 

To trigger the native device date-picker for mobile phones, the `date-picker` attr must be applied to an input element. If it's on a span/div/etc, the desktop datepicker (tether popover) will display.

See:
date-picker.ts, line 335, `if ($element.is('input[type="text"]'))`

**Comment by EBMike** [comment]
v2.0.5
